"""empty message

Revision ID: f16282324095
Revises: f3665cf819a7
Create Date: 2019-10-08 15:17:30.729188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f16282324095'
down_revision = 'f3665cf819a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plants', sa.Column('category', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plants', 'category')
    # ### end Alembic commands ###
